/* Optional browser suite. Install playwright locally and set QUANTIK_CHROMIUM if needed. */
const {chromium}=require(process.env.QUANTIK_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
require('node:fs').mkdirSync('/tmp/quantik-qa',{recursive:true});
const root=path.resolve(__dirname,'..');
require('node:fs').mkdirSync(path.join(root,'docs/previews'),{recursive:true});
const waitReady=(child,pattern)=>new Promise((resolve,reject)=>{
 let log='';const timer=setTimeout(()=>reject(Error('Server did not start: '+log)),15000);
 for(const stream of [child.stdout,child.stderr])stream.on('data',b=>{log+=b.toString();if(pattern.test(log)){clearTimeout(timer);resolve();}});
 child.on('exit',code=>{clearTimeout(timer);reject(Error(`Server exited ${code}: ${log}`));});
});
(async()=>{
 const vite=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5173','--strictPort'],{cwd:root});
 const api=spawn(process.env.QUANTIK_PYTHON||'python',['-m','uvicorn','server:app','--host','127.0.0.1','--port','8000'],{cwd:path.join(root,'backend')});
 let browser;
 try{
 await Promise.all([waitReady(vite,/Local:/),waitReady(api,/Uvicorn running/)]);
 browser=await chromium.launch({headless:true,...(process.env.QUANTIK_CHROMIUM?{executablePath:process.env.QUANTIK_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));let quantStarts=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/quant/jobs'))quantStarts++;});
 await page.route('https://s3.tradingview.com/**',r=>r.abort()); // external provider functionality is a separate manual check
 await page.route('https://fonts.googleapis.com/**',r=>r.abort());
 await page.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});
 await page.getByText('QuanTik fixture',{exact:false}).waitFor();
 assert.equal(await page.locator('tbody:visible tr').count(),21);
 const nav=text=>page.locator('nav button').filter({hasText:text});
 let scanReads=0;page.on('request',r=>{if(/\/scan\/latest(?:\/highlights)?$/.test(r.url())){assert.equal(r.method(),'GET');scanReads++;}});
 await nav('Quét toàn sàn').click();
 const scan=page.getByRole('region',{name:'Quét toàn sàn',exact:true});
 assert.equal(scanReads,0);assert.equal(await scan.locator('table').count(),0);
 assert((await scan.locator('h2').evaluate(el=>getComputedStyle(el).fontFamily)).includes('IBM Plex Mono'));
 await page.screenshot({path:'/tmp/quantik-qa/scan-activation.png',fullPage:true});
 await page.screenshot({path:path.join(root,'docs/previews/scan-activation.jpg'),type:'jpeg',quality:85,fullPage:true});
 await scan.getByRole('button',{name:'Kích hoạt kết quả'}).click();
 await scan.getByRole('heading',{name:'5 nổi bật · 5 thận trọng'}).waitFor();
 assert.equal(await scan.locator('.quant-inline').count(),10);
 assert.equal(scanReads,1);assert.equal(quantStarts,0);
 await scan.getByLabel('SÀN',{exact:true}).selectOption('HNX');
 for(const row of await scan.locator('tbody tr').all())assert((await row.innerText()).includes('HNX'));
 await scan.getByRole('button',{name:'Đặt lại'}).click();
 await scan.getByLabel('TÌM TRONG 10 MÃ').fill('hoa phat');assert.equal(await scan.locator('tbody tr').count(),1);
 await scan.getByRole('button',{name:'Đặt lại'}).click();
 await scan.getByLabel('NHÓM CHỈ SỐ').selectOption('forecast');
 assert(await scan.getByRole('button',{name:'Lợi nhuận dự báo (%)',exact:true}).count()>0);
 await scan.getByLabel('NHÓM CHỈ SỐ').selectOption('core');
 await scan.getByRole('button',{name:'Xem chart FPT',exact:true}).click();
 await page.getByRole('dialog',{name:'FPT',exact:true}).waitFor();
 await page.getByRole('dialog',{name:'FPT',exact:true}).getByRole('button',{name:'Đóng',exact:true}).click();
 assert.equal(quantStarts,0);
 await nav('Thị trường').click();await nav('Quét toàn sàn').click();assert.equal(scanReads,1);
 await page.screenshot({path:'/tmp/quantik-qa/scan-results.png',fullPage:true});
 await page.screenshot({path:path.join(root,'docs/previews/scan-results.jpg'),type:'jpeg',quality:85,fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'/tmp/quantik-qa/scan-mobile.png',fullPage:true});
 await page.route('**/api/scan/latest/highlights',r=>r.fulfill({status:503,body:'snapshot unavailable'}));
 await scan.getByRole('button',{name:'Lấy bản công bố mới'}).click();
 await scan.getByRole('alert').waitFor();assert.equal(await scan.locator('tbody tr').count(),10);
 await page.reload({waitUntil:'domcontentloaded'});await nav('Quét toàn sàn').click();
 const requestsBefore=scanReads;assert.equal(await scan.locator('table').count(),0);
 await page.screenshot({path:'/tmp/quantik-qa/scan-mobile-gate.png',fullPage:true});
 await page.screenshot({path:path.join(root,'docs/previews/scan-mobile.jpg'),type:'jpeg',quality:85,fullPage:true});
 await scan.getByRole('button',{name:'Kích hoạt kết quả'}).click();await scan.getByRole('alert').waitFor();
 assert.equal(await scan.locator('table').count(),0);assert.equal(scanReads,requestsBefore+1);assert.equal(quantStarts,0);
 await scan.getByRole('button',{name:'Xem bản mẫu minh họa'}).click();await scan.getByRole('heading',{name:'5 nổi bật · 5 thận trọng'}).waitFor();
 assert.equal(await scan.locator('.quant-inline').count(),10);
 assert.equal(scanReads,requestsBefore+1);
 await page.unroute('**/api/scan/latest/highlights');
 await page.setViewportSize({width:1440,height:1000});await nav('Thị trường').click();
 await nav('Bảng điện').click();
 await page.getByLabel('Lọc sàn').selectOption('HNX');
 assert.equal(await page.locator('.traditional-board tbody tr').count(),3);
 await page.getByLabel('Lọc sàn').selectOption('ALL');
 await page.getByLabel('Lọc ngành').selectOption('banks');
 assert.equal(await page.locator('.traditional-board tbody tr').count(),5);
 await page.getByRole('button',{name:'Xóa lọc'}).click();
 await page.getByRole('checkbox',{name:'Nước ngoài',exact:true}).check();
 await page.screenshot({path:'/tmp/quantik-qa/board-desktop.png',fullPage:true});
 await nav('Nhóm ngành').click();
 assert.equal(await page.locator('.sector-table tbody tr').count(),10);
 await page.locator('.sector-link').filter({hasText:'Ngân hàng'}).click();
 assert.equal(await page.locator('.traditional-board tbody tr').count(),5);
 await page.getByRole('button',{name:'Xóa lọc'}).click();
 assert.equal(await nav('Tra cứu công thức').count(),0);
 await nav('Phân tích Quant').click();
 await page.getByRole('button',{name:'Xem kết quả mẫu'}).click();
 const report=page.getByRole('region',{name:'Báo cáo phân tích FPT'});
 await page.locator('.analysis-report').waitFor();
 const sections=page.locator('.analysis-page .report-toggle');assert.equal(await sections.count(),4);
 assert.equal(await sections.nth(0).getAttribute('aria-expanded'),'true');
 await sections.nth(1).click();assert.equal(await sections.nth(0).getAttribute('aria-expanded'),'true');
 await sections.nth(0).click();assert.equal(await sections.nth(1).getAttribute('aria-expanded'),'true');
 await sections.nth(0).click();
 const sharpe=page.getByRole('button',{name:'Sharpe',exact:true}).first();
 await sharpe.hover();await page.getByRole('tooltip').waitFor();
 assert.equal(await page.getByRole('tooltip').locator('.katex').count(),1);
 assert.equal(await sharpe.locator('.term-mark').count(),0);
 assert((await sharpe.evaluate(el=>getComputedStyle(el).textDecorationLine)).includes('underline'));
 await page.screenshot({path:'/tmp/quantik-qa/formula-popup.png',fullPage:true});
 await page.keyboard.press('Escape');
 await sections.nth(2).click();
 await page.getByRole('button',{name:'HMM',exact:true}).first().hover();
 await page.getByRole('tooltip').waitFor();assert(await page.getByRole('tooltip').getByText('HMM Regime',{exact:true}).isVisible());
 await page.keyboard.press('Escape');
  await nav('Thị trường').click();
 await page.locator('.symbol-link').filter({hasText:'FPT'}).first().click();
 const stock=page.getByRole('dialog',{name:'FPT',exact:true});await stock.waitFor();
 await stock.locator('.workspace-tools').getByRole('button',{name:'Chạy Quant FPT',exact:true}).click();
 await stock.getByText('Theo dõi (mô phỏng)',{exact:false}).waitFor();
 const jobs=await page.request.get('http://127.0.0.1:8000/api/board');assert.equal(jobs.status(),200);
 const before=await stock.locator('.tradingview-widget-container').evaluate(el=>{el.dataset.testIdentity='same';return el.dataset.testIdentity;});
 await stock.getByRole('button',{name:'Thu gọn panel',exact:true}).click();
 assert(await stock.locator('.analysis-drawer').isHidden());
 await stock.getByRole('button',{name:'Mở phân tích',exact:false}).click();
 assert.equal(await stock.locator('.tradingview-widget-container').getAttribute('data-test-identity'),before);
 assert(await stock.getByText('Theo dõi (mô phỏng)',{exact:false}).isVisible());assert.equal(quantStarts,1);
 const separator=stock.getByRole('separator');await separator.focus();const old=Number(await separator.getAttribute('aria-valuenow'));await page.keyboard.press('ArrowLeft');assert.equal(Number(await separator.getAttribute('aria-valuenow')),old+20);
 const box=await separator.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x-30,box.y+box.height/2);await page.mouse.up();
 assert.equal(await stock.locator('.tradingview-widget-container').getAttribute('data-test-identity'),before);
 await stock.getByLabel('Khung nến').selectOption('15');assert.equal(await stock.getByLabel('Khung nến').inputValue(),'15');
 assert.equal(await stock.locator('.research-card').count(),6);assert.equal(await stock.locator('.qimg').count(),0);
 const stockSections=stock.locator('.report-toggle');await stockSections.nth(0).click();await stockSections.nth(0).click();
 await stock.getByRole('button',{name:'Sharpe',exact:true}).hover();await page.getByRole('tooltip').waitFor();
 await stock.getByRole('button',{name:'Sharpe',exact:true}).click();await page.getByRole('tooltip').waitFor();
 await page.keyboard.press('Escape');assert(await stock.isVisible());
  await page.screenshot({path:'/tmp/quantik-qa/chart-panel.png',fullPage:true});
 await stock.getByRole('button',{name:'Đóng',exact:true}).click();
 await nav('Thị trường').click();
 await page.getByRole('button',{name:'Theo dõi FPT',exact:true}).click();
 await nav('Theo dõi').click();assert.equal(await page.locator('tbody:visible tr').count(),2);
 await page.getByRole('button',{name:'Chuyển chế độ sáng'}).click();
 await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await nav('Theo dõi').click();assert.equal(await page.locator('tbody:visible tr').count(),2);
 await page.setViewportSize({width:390,height:844});await nav('Bảng điện').click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'/tmp/quantik-qa/mobile-board.png',fullPage:true});
 await page.locator('.symbol-link').filter({hasText:'FPT'}).first().click();await stock.waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.equal(await stock.getByRole('separator').getAttribute('aria-orientation'),'horizontal');assert(Math.abs((await stock.boundingBox()).y)<2);
 await page.screenshot({path:'/tmp/quantik-qa/mobile-chart.png',fullPage:false});
 await stock.getByRole('button',{name:'Đóng',exact:true}).click();
 // Offline state must retain the last snapshot and let users view local sample.
 await page.route('**/api/**',r=>r.fulfill({status:503,body:'offline'}));
 await nav('Thị trường').click();await page.getByText('Nguồn chưa cập nhật · Giữ snapshot',{exact:false}).waitFor();
 await nav('Phân tích Quant').click();
 await page.getByRole('button',{name:'Chạy lại',exact:true}).click();
 await page.getByRole('button',{name:'Thử lại',exact:true}).waitFor();
 await page.getByRole('button',{name:'Xem kết quả mẫu',exact:true}).click();
 await page.getByText('Mẫu tĩnh, không chạy mô hình',{exact:false}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: scan activation GET only, no engine jobs, filters, session retention, reload gate, error retry, refresh preserves results, explicit demo, desktop/mobile brand; real demo API job; sector/exchange filtering; grouped order book; inline formula hover/touch/Escape; independent report accordions and structured visuals; collapse and resize preserve chart/results; timeframe; persistence; mobile overflow; offline fallback. External TradingView script aborted for deterministic tests.');
 }finally{await browser?.close();vite.kill();api.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
