/* Optional browser suite. Install playwright locally and set QUANTIK_CHROMIUM if needed. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
require('node:fs').mkdirSync('/tmp/quantik-qa',{recursive:true});
const root=path.resolve(__dirname,'..');
const waitReady=(child,pattern)=>new Promise((resolve,reject)=>{
 let log='';const timer=setTimeout(()=>reject(Error('Server did not start: '+log)),15000);
 for(const stream of [child.stdout,child.stderr])stream.on('data',b=>{log+=b.toString();if(pattern.test(log)){clearTimeout(timer);resolve();}});
 child.on('exit',code=>{clearTimeout(timer);reject(Error(`Server exited ${code}: ${log}`));});
});
(async()=>{
 const vite=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5173','--strictPort'],{cwd:root});
 const api=spawn(process.env.QUANTIK_PYTHON||'python',['-m','uvicorn','server:app','--host','127.0.0.1','--port','8000'],{cwd:path.join(root,'backend')});
 let browser;
 try{
 await Promise.all([waitReady(vite,/Local:/),waitReady(api,/Uvicorn running/)]);
 browser=await chromium.launch({headless:true,...(process.env.QUANTIK_CHROMIUM?{executablePath:process.env.QUANTIK_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));let quantStarts=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/quant/jobs'))quantStarts++;});
 await page.route('https://s3.tradingview.com/**',r=>r.abort()); // external provider functionality is a separate manual check
 await page.route('https://fonts.googleapis.com/**',r=>r.abort());
 await page.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});
 await page.getByText('QuanTik fixture',{exact:false}).waitFor();
 assert.equal(await page.locator('tbody tr').count(),21);
 const nav=text=>page.locator('nav button').filter({hasText:text});
 await nav('Bảng điện').click();
 await page.getByLabel('Lọc sàn').selectOption('HNX');
 assert.equal(await page.locator('.traditional-board tbody tr').count(),3);
 await page.getByLabel('Lọc sàn').selectOption('ALL');
 await page.getByLabel('Lọc ngành').selectOption('banks');
 assert.equal(await page.locator('.traditional-board tbody tr').count(),5);
 await page.getByRole('button',{name:'Xóa lọc'}).click();
 await page.getByRole('checkbox',{name:'Nước ngoài',exact:true}).check();
 await page.screenshot({path:'/tmp/quantik-qa/board-desktop.png',fullPage:true});
 await nav('Nhóm ngành').click();
 assert.equal(await page.locator('.sector-table tbody tr').count(),10);
 await page.locator('.sector-link').filter({hasText:'Ngân hàng'}).click();
 assert.equal(await page.locator('.traditional-board tbody tr').count(),5);
 await page.getByRole('button',{name:'Xóa lọc'}).click();
 await nav('Tra cứu công thức').click();
 const sharpe=page.getByRole('button',{name:'Sharpe',exact:false}).first();
 await sharpe.hover();await page.getByRole('tooltip').waitFor();
 assert.equal(await page.getByRole('tooltip').locator('.katex').count(),1);
 await sharpe.click();await page.getByRole('dialog',{name:'Sharpe',exact:true}).waitFor();
 await page.screenshot({path:'/tmp/quantik-qa/formula-popup.png',fullPage:true});
 await page.keyboard.press('Escape');
 await nav('Thị trường').click();
 await page.locator('.symbol-link').filter({hasText:'FPT'}).first().click();
 const stock=page.getByRole('dialog',{name:'FPT',exact:true});await stock.waitFor();
 await stock.getByRole('button',{name:'Chạy phân tích FPT'}).click();
 await stock.getByText('Theo dõi (mô phỏng)',{exact:false}).waitFor();
 const jobs=await page.request.get('http://127.0.0.1:8000/api/board');assert.equal(jobs.status(),200);
 const before=await stock.locator('.tradingview-widget-container').evaluate(el=>{el.dataset.testIdentity='same';return el.dataset.testIdentity;});
 await stock.getByRole('button',{name:'Thu gọn panel',exact:true}).click();
 assert(await stock.locator('.analysis-drawer').isHidden());
 await stock.getByRole('button',{name:'Mở phân tích',exact:false}).click();
 assert.equal(await stock.locator('.tradingview-widget-container').getAttribute('data-test-identity'),before);
 assert(await stock.getByText('Theo dõi (mô phỏng)',{exact:false}).isVisible());assert.equal(quantStarts,1);
 const separator=stock.getByRole('separator');await separator.focus();const old=Number(await separator.getAttribute('aria-valuenow'));await page.keyboard.press('ArrowLeft');assert.equal(Number(await separator.getAttribute('aria-valuenow')),old+20);
 const box=await separator.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x-30,box.y+box.height/2);await page.mouse.up();
 assert.equal(await stock.locator('.tradingview-widget-container').getAttribute('data-test-identity'),before);
 await stock.getByLabel('Khung nến').selectOption('15');assert.equal(await stock.getByLabel('Khung nến').inputValue(),'15');
 await stock.getByRole('button',{name:'Sharpe',exact:false}).hover();await page.getByRole('tooltip').waitFor();
 await stock.getByRole('button',{name:'Sharpe',exact:false}).click();await page.getByRole('dialog',{name:'Sharpe',exact:true}).waitFor();
 await page.keyboard.press('Escape');assert(await stock.isVisible());
 await page.screenshot({path:'/tmp/quantik-qa/chart-panel.png',fullPage:true});
 await stock.getByRole('button',{name:'Đóng',exact:true}).click();
 await nav('Thị trường').click();
 await page.getByRole('button',{name:'Theo dõi FPT',exact:true}).click();
 await nav('Theo dõi').click();assert.equal(await page.locator('tbody tr').count(),2);
 await page.getByRole('button',{name:'Chuyển chế độ sáng'}).click();
 await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await nav('Theo dõi').click();assert.equal(await page.locator('tbody tr').count(),2);
 await page.setViewportSize({width:390,height:844});await nav('Bảng điện').click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'/tmp/quantik-qa/mobile-board.png',fullPage:true});
 await page.locator('.symbol-link').filter({hasText:'FPT'}).first().click();await stock.waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.equal(await stock.getByRole('separator').getAttribute('aria-orientation'),'horizontal');assert(Math.abs((await stock.boundingBox()).y)<2);
 await page.screenshot({path:'/tmp/quantik-qa/mobile-chart.png',fullPage:false});
 await stock.getByRole('button',{name:'Đóng',exact:true}).click();
 // Offline state must retain the last snapshot and let users view local sample.
 await page.route('**/api/**',r=>r.fulfill({status:503,body:'offline'}));
 await nav('Thị trường').click();await page.getByText('Mất kết nối · Giữ snapshot',{exact:false}).waitFor();
 await nav('Phân tích Quant').click();await page.getByRole('button',{name:'Xem kết quả mẫu'}).click();
 await page.getByText('Mẫu tĩnh, không chạy mô hình',{exact:false}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: real demo API job; sector/exchange filtering; grouped order book; formula hover/click/Escape; collapse and resize preserve chart/results; timeframe; persistence; mobile overflow; offline fallback. External TradingView script aborted for deterministic tests.');
 }finally{await browser?.close();vite.kill();api.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
