import TermHint from './TermHint.jsx';
import {change,fmt,priceClass} from '../market.js';
export default function PriceBoardTable({rows,watch,toggleWatch,onOpen,onSelect,onQuant,selected,sort,onSort,book,stats,foreign,dense,flash={}}){
 const columns=8+(book?12:0)+(stats?5:0)+(foreign?3:0);
 const number=(v,r,unit=1000)=> <span className={priceClass(v,r)}>{fmt(v==null?null:v/unit)}</span>;
 const quote=(q,r)=>q?.kind==='ato'||q?.kind==='atc'?q.kind.toUpperCase():number(q?.price,r);
 const sorted=(key,label)=> <button className="sort-button" onClick={()=>onSort(key)}>{label}{sort.k===key?(sort.d===1?' ↑':' ↓'):''}</button>;
 return <div className={`boardwrap traditional-wrap ${dense?'dense':''}`}><table className="traditional-board"><thead><tr><th rowSpan={2} className="sticky-symbol" aria-sort={sort.k==='symbol'?(sort.d===1?'ascending':'descending'):'none'}>{sorted('symbol','Mã')}</th><th colSpan={3}>Giá phiên</th>{book&&<th colSpan={6}><TermHint id="bid"/></th>}<th colSpan={3}><TermHint id="matched"/></th>{book&&<th colSpan={6}><TermHint id="ask"/></th>}{stats&&<th colSpan={5}><TermHint id="liquidity">Thống kê phiên</TermHint></th>}{foreign&&<th colSpan={3}>Nước ngoài</th>}<th rowSpan={2}><TermHint id="quant_score">Quant</TermHint><button className="sort-button" aria-label="Sắp xếp điểm Quant" onClick={()=>onSort('score')}> ↕</button></th></tr><tr><th><TermHint id="ref">TC</TermHint></th><th><TermHint id="ceil"/></th><th><TermHint id="floor"/></th>{book&&[3,2,1].map(i=><th key={`b${i}`} colSpan={2}>Giá {i} / KL {i}</th>)}<th>{sorted('price','Giá')}</th><th>KL lần khớp</th><th>{sorted('change','+/− %')}</th>{book&&[1,2,3].map(i=><th key={`a${i}`} colSpan={2}>Giá {i} / KL {i}</th>)}{stats&&<><th>{sorted('vol','Tổng KL')}</th><th>{sorted('value','GTGD (triệu ₫)')}</th><th>Mở</th><th>Cao</th><th>Thấp</th></>}{foreign&&<><th>Mua (CP)</th><th>Bán (CP)</th><th>Room (CP)</th></>}</tr></thead><tbody>{!rows.length&&<tr><td colSpan={columns}><div className="empty">Không có mã phù hợp bộ lọc.</div></td></tr>}{rows.map(r=><tr key={r.symbol} className={selected===r.symbol?'selected':''} tabIndex={0} onClick={()=>onSelect(r.symbol)} onDoubleClick={()=>onOpen(r.symbol)} onKeyDown={e=>e.target===e.currentTarget&&e.key==='Enter'&&onOpen(r.symbol)}><td className="sym sticky-symbol"><button className="star" aria-label={`Theo dõi ${r.symbol}`} aria-pressed={watch.has(r.symbol)} onClick={e=>{e.stopPropagation();toggleWatch(r.symbol);}}>{watch.has(r.symbol)?'★':'☆'}</button><button className="symbol-link" onClick={e=>{e.stopPropagation();onOpen(r.symbol);}}>{r.symbol}</button><small>{r.exchange}</small></td><td>{number(r.ref,r)}</td><td>{number(r.ceil,r)}</td><td>{number(r.floor,r)}</td>{book&&[2,1,0].map(i=><FragmentCells key={`bid${i}`} price={quote(r.bids?.[i],r)} volume={r.bids?.[i]?.volume}/>)}<td className={`price ${flash[r.symbol]||''}`}>{number(r.price,r)}</td><td>{fmt(r.lastVolume,0)}</td><td className={priceClass(r.price,r)}>{change(r)==null?'—':`${change(r)>=0?'+':''}${fmt(change(r)*100)}%`}</td>{book&&[0,1,2].map(i=><FragmentCells key={`ask${i}`} price={quote(r.asks?.[i],r)} volume={r.asks?.[i]?.volume}/>)}{stats&&<><td>{fmt(r.vol,0)}</td><td>{fmt(r.value==null?null:r.value/1e6)}</td><td>{number(r.open,r)}</td><td>{number(r.high,r)}</td><td>{number(r.low,r)}</td></>}{foreign&&<><td>{fmt(r.foreignBuy,0)}</td><td>{fmt(r.foreignSell,0)}</td><td>{fmt(r.foreignRoom,0)}</td></>}<td><button className="qbtn" aria-label={`Phân tích ${r.symbol}`} onClick={e=>{e.stopPropagation();onQuant(r.symbol);}}>{r.score??'—'} ›</button></td></tr>)}</tbody></table></div>;
}
function FragmentCells({price,volume}){return <><td>{price}</td><td>{fmt(volume,0)}</td></>;}
